name: Saludo usando secretos
run-name: ¡Estoy aprendiendo a usar Secrets!
on:
  workflow_dispatch
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Quiubo
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Tu apellido es ${{ vars.APELLIDO }}. Tu contrasena es ${{ secrets.PASSWORD }}"
        env:
          NOMBRE: Erick